markdown: kramdown
highlighter: rouge
permalink: /blog/:title
title: BLACK FIRE on WHITE FIRE
date: Jun 1-3
year: 2016
tickets: false
speakers: true
workshops: true
schedule: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
kramdown:
  input: GFM
