markdown: kramdown
highlighter: pygments
permalink: /blog/:title
tickets: true
speakers: true
schedule: false
workshops: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
kramdown:
  input: GFM
