markdown: kramdown
highlighter: pygments
permalink: /blog/:title
title: BLACK FIRE on WHITE FIRE
date: Jun 1-3
year: 2016
tickets: true
speakers: true
schedule: false
workshops: true
schedule: false
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
kramdown:
  input: GFM
